-- Ejecutar como SYSTEM o SYS en XE
-- Ejemplo:
-- sqlplus system/TU_CLAVE@XE @fix_usuario_practicas_app.sql

SET SERVEROUTPUT ON;
DECLARE
  n NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO n FROM dba_users WHERE username = 'PRACTICAS_APP';

  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER PRACTICAS_APP IDENTIFIED BY Practicas2026';
    DBMS_OUTPUT.PUT_LINE('Usuario PRACTICAS_APP creado.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Usuario PRACTICAS_APP ya existe.');
  END IF;

  EXECUTE IMMEDIATE 'ALTER USER PRACTICAS_APP IDENTIFIED BY Practicas2026 ACCOUNT UNLOCK';
  DBMS_OUTPUT.PUT_LINE('Password reiniciada y cuenta desbloqueada.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Detalle: ' || SQLERRM);
END;
/

GRANT CONNECT, RESOURCE TO PRACTICAS_APP;
GRANT CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO PRACTICAS_APP;

PROMPT ====== PRUEBA ======
PROMPT Intenta luego: CONNECT PRACTICAS_APP/Practicas2026@XE
