SET DEFINE OFF;

PROMPT ============================================================
PROMPT SIGPRA - DEMO PROCEDIMIENTOS, ROLES Y USUARIOS ORACLE
PROMPT Compatible con el esquema actual PRACTICAS_APP en Oracle XE
PROMPT ============================================================

PROMPT 1) ROLES DE APLICACION

DECLARE
  PROCEDURE create_role_if_missing(p_role VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_roles WHERE role = UPPER(p_role);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE ROLE ' || p_role;
    END IF;
  END;
BEGIN
  create_role_if_missing('ROL_SIGPRA_ESTUDIANTE');
  create_role_if_missing('ROL_SIGPRA_DOCENTE');
  create_role_if_missing('ROL_SIGPRA_DIRECTOR');
  create_role_if_missing('ROL_SIGPRA_AUDITOR');
END;
/

PROMPT 2) USUARIOS DE DEMOSTRACION

DECLARE
  PROCEDURE create_user_if_missing(p_user VARCHAR2, p_password VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = UPPER(p_user);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE USER ' || p_user ||
        ' IDENTIFIED BY "' || p_password || '" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
      EXECUTE IMMEDIATE 'ALTER USER ' || p_user || ' QUOTA UNLIMITED ON USERS';
    END IF;
  END;
BEGIN
  create_user_if_missing('U_SIGPRA_EST', 'Sigpra2026*Est');
  create_user_if_missing('U_SIGPRA_DOC', 'Sigpra2026*Doc');
  create_user_if_missing('U_SIGPRA_DIR', 'Sigpra2026*Dir');
  create_user_if_missing('U_SIGPRA_AUD', 'Sigpra2026*Aud');
END;
/

PROMPT 3) PERMISOS A ROLES

GRANT CREATE SESSION TO ROL_SIGPRA_ESTUDIANTE;
GRANT CREATE SESSION TO ROL_SIGPRA_DOCENTE;
GRANT CREATE SESSION TO ROL_SIGPRA_DIRECTOR;
GRANT CREATE SESSION TO ROL_SIGPRA_AUDITOR;

GRANT SELECT ON usuario TO ROL_SIGPRA_ESTUDIANTE;
GRANT SELECT ON estudiante TO ROL_SIGPRA_ESTUDIANTE;
GRANT SELECT ON practica TO ROL_SIGPRA_ESTUDIANTE;
GRANT SELECT, INSERT, UPDATE ON bitacora TO ROL_SIGPRA_ESTUDIANTE;
GRANT SELECT, INSERT ON evidencia TO ROL_SIGPRA_ESTUDIANTE;

GRANT SELECT ON usuario TO ROL_SIGPRA_DOCENTE;
GRANT SELECT ON estudiante TO ROL_SIGPRA_DOCENTE;
GRANT SELECT ON practica TO ROL_SIGPRA_DOCENTE;
GRANT SELECT, UPDATE ON bitacora TO ROL_SIGPRA_DOCENTE;

GRANT SELECT, INSERT, UPDATE ON usuario TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON estudiante TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON docente_asesor TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON entidad_receptora TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON practica TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON plantilla_bitacora TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON pregunta_plantilla_bitacora TO ROL_SIGPRA_DIRECTOR;

GRANT SELECT ON usuario TO ROL_SIGPRA_AUDITOR;
GRANT SELECT ON estudiante TO ROL_SIGPRA_AUDITOR;
GRANT SELECT ON docente_asesor TO ROL_SIGPRA_AUDITOR;
GRANT SELECT ON entidad_receptora TO ROL_SIGPRA_AUDITOR;
GRANT SELECT ON practica TO ROL_SIGPRA_AUDITOR;
GRANT SELECT ON bitacora TO ROL_SIGPRA_AUDITOR;
GRANT SELECT ON evidencia TO ROL_SIGPRA_AUDITOR;

GRANT ROL_SIGPRA_ESTUDIANTE TO U_SIGPRA_EST;
GRANT ROL_SIGPRA_DOCENTE TO U_SIGPRA_DOC;
GRANT ROL_SIGPRA_DIRECTOR TO U_SIGPRA_DIR;
GRANT ROL_SIGPRA_AUDITOR TO U_SIGPRA_AUD;

PROMPT 4) PROCEDIMIENTOS ALMACENADOS

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_ACTIVIDAD (
  P_ID_PRACTICA       IN  NUMBER,
  P_FECHA_ACTIVIDAD   IN  DATE,
  P_ACTIVIDAD         IN  VARCHAR2,
  P_DESCRIPCION       IN  VARCHAR2,
  P_HORAS             IN  NUMBER,
  P_ID_BITACORA_OUT   OUT NUMBER
) IS
BEGIN
  INSERT INTO bitacora (
    id_bitacora, id_practica, fecha_actividad, actividad,
    descripcion, horas_reportadas, estado_validacion
  ) VALUES (
    NULL, P_ID_PRACTICA, P_FECHA_ACTIVIDAD, P_ACTIVIDAD,
    P_DESCRIPCION, P_HORAS, 'PENDIENTE'
  )
  RETURNING id_bitacora INTO P_ID_BITACORA_OUT;

  UPDATE practica
     SET horas_acumuladas = NVL(horas_acumuladas, 0) + P_HORAS,
         estado = CASE
                    WHEN NVL(horas_acumuladas, 0) + P_HORAS >= horas_objetivo
                    THEN 'PENDIENTE_APROBACION'
                    ELSE estado
                  END
   WHERE id_practica = P_ID_PRACTICA;
END;
/

CREATE OR REPLACE PROCEDURE SP_VALIDAR_ACTIVIDAD (
  P_ID_BITACORA       IN NUMBER,
  P_ID_DOCENTE        IN NUMBER,
  P_ESTADO_VALIDACION IN VARCHAR2,
  P_OBSERVACION       IN VARCHAR2
) IS
BEGIN
  UPDATE bitacora
     SET estado_validacion = P_ESTADO_VALIDACION,
         observacion_docente = P_OBSERVACION,
         id_docente_validador = P_ID_DOCENTE,
         fecha_validacion = SYSTIMESTAMP
   WHERE id_bitacora = P_ID_BITACORA;
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_EVIDENCIA (
  P_ID_BITACORA       IN  NUMBER,
  P_NOMBRE_ARCHIVO    IN  VARCHAR2,
  P_TIPO_ARCHIVO      IN  VARCHAR2,
  P_URL_ARCHIVO       IN  VARCHAR2,
  P_ID_EVIDENCIA_OUT  OUT NUMBER
) IS
BEGIN
  INSERT INTO evidencia (
    id_evidencia, nombre_archivo, tipo_archivo, url_archivo, fecha_carga, id_actividad
  ) VALUES (
    NULL, P_NOMBRE_ARCHIVO, P_TIPO_ARCHIVO, P_URL_ARCHIVO, SYSTIMESTAMP, P_ID_BITACORA
  )
  RETURNING id_evidencia INTO P_ID_EVIDENCIA_OUT;
END;
/

CREATE OR REPLACE PROCEDURE SP_CERRAR_PRACTICA (
  P_ID_PRACTICA   IN NUMBER,
  P_ESTADO_FINAL  IN VARCHAR2
) IS
BEGIN
  UPDATE practica
     SET estado = P_ESTADO_FINAL,
         fecha_fin = NVL(fecha_fin, SYSDATE)
   WHERE id_practica = P_ID_PRACTICA;
END;
/

CREATE OR REPLACE PROCEDURE SP_CREAR_PLANTILLA_BITACORA (
  P_NOMBRE            IN  VARCHAR2,
  P_SEMESTRE          IN  NUMBER,
  P_MODALIDAD         IN  VARCHAR2,
  P_ID_CREADO_POR     IN  NUMBER,
  P_ID_PLANTILLA_OUT  OUT NUMBER
) IS
BEGIN
  INSERT INTO plantilla_bitacora (
    id_plantilla, nombre, semestre_practica, modalidad,
    version, estado, id_creado_por, fecha_creacion
  ) VALUES (
    NULL, P_NOMBRE, P_SEMESTRE, P_MODALIDAD,
    '1', 'ACTIVA', P_ID_CREADO_POR, SYSDATE
  )
  RETURNING id_plantilla INTO P_ID_PLANTILLA_OUT;
END;
/

PROMPT 5) PERMISOS DE EJECUCION SOBRE PROCEDIMIENTOS

GRANT EXECUTE ON SP_REGISTRAR_ACTIVIDAD TO ROL_SIGPRA_ESTUDIANTE;
GRANT EXECUTE ON SP_REGISTRAR_EVIDENCIA TO ROL_SIGPRA_ESTUDIANTE;
GRANT EXECUTE ON SP_VALIDAR_ACTIVIDAD TO ROL_SIGPRA_DOCENTE;
GRANT EXECUTE ON SP_CERRAR_PRACTICA TO ROL_SIGPRA_DIRECTOR;
GRANT EXECUTE ON SP_CREAR_PLANTILLA_BITACORA TO ROL_SIGPRA_DIRECTOR;

COMMIT;

PROMPT 6) VALIDACION RAPIDA

SET LINESIZE 220
SET PAGESIZE 100
COLUMN object_name FORMAT A35
COLUMN object_type FORMAT A20
COLUMN status FORMAT A12
SELECT object_name, object_type, status
FROM user_objects
WHERE object_type = 'PROCEDURE'
ORDER BY object_name;

COLUMN role FORMAT A35
SELECT role
FROM dba_roles
WHERE role LIKE 'ROL_SIGPRA%'
ORDER BY role;

COLUMN username FORMAT A30
COLUMN account_status FORMAT A20
SELECT username, account_status
FROM dba_users
WHERE username LIKE 'U_SIGPRA%'
ORDER BY username;

