@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Estudiante" as Estudiante
actor "Docente Asesor" as Docente
actor "Directora de Programa" as Directora

rectangle "Sistema de Gestion de Practicas Academicas (Reducido)" {
  usecase "UC-01 Iniciar Sesion" as UC01
  usecase "UC-02 Registrar Estudiante" as UC02
  usecase "UC-03 Registrar Docente Asesor" as UC03
  usecase "UC-04 Registrar Practica Academica" as UC04
  usecase "UC-05 Registrar Bitacora y Horas" as UC05
  usecase "UC-06 Cargar Evidencias" as UC06
  usecase "UC-07 Validar o Rechazar Actividades" as UC07
  usecase "UC-08 Aprobar Cierre de Practica" as UC08
  usecase "UC-09 Consultar Estado e Historial" as UC09
  usecase "UC-10 Generar Reportes por Filtros" as UC10
}

Estudiante -- UC01
Estudiante -- UC02
Estudiante -- UC05
Estudiante -- UC06
Estudiante -- UC09

Docente -- UC01
Docente -- UC07
Docente -- UC09

Directora -- UC01
Directora -- UC03
Directora -- UC04
Directora -- UC08
Directora -- UC09
Directora -- UC10

UC05 .> UC06 : <<include>>
UC08 .> UC07 : <<include>>
UC10 .> UC09 : <<include>>

@enduml
