SET DEFINE OFF;

PROMPT ================================================
PROMPT TERCERA ENTREGA - BASE DE DATOS II (SIGPRA)
PROMPT ================================================
PROMPT Este script complementa los scripts de tablas y datos
PROMPT para cubrir: usuarios/perfiles, roles, privilegios,
PROMPT procedimientos almacenados, disparadores y reportes.
PROMPT ================================================

PROMPT 1) MODELO RELACIONAL Y TABLAS
PROMPT Ejecuta primero (si no se ha ejecutado):
PROMPT @@..\ENTREGA_2_COMPLETA\03_BASE_DATOS\bd\01_crear_esquema_oracle.sql
PROMPT @@..\ENTREGA_2_COMPLETA\03_BASE_DATOS\bd\02_datos_iniciales.sql
PROMPT @@..\ENTREGA_2_COMPLETA\03_BASE_DATOS\bd\04_ajustes_reunion_20260310.sql

PROMPT 2.1) CREACION DE USUARIOS CON PERFILES

CREATE PROFILE PERFIL_SIGPRA_ESTUDIANTE LIMIT
  SESSIONS_PER_USER 2
  CONNECT_TIME 240
  IDLE_TIME 30
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LIFE_TIME 90;

CREATE PROFILE PERFIL_SIGPRA_DOCENTE LIMIT
  SESSIONS_PER_USER 3
  CONNECT_TIME 360
  IDLE_TIME 45
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LIFE_TIME 90;

CREATE PROFILE PERFIL_SIGPRA_DIRECTOR LIMIT
  SESSIONS_PER_USER 4
  CONNECT_TIME 480
  IDLE_TIME 60
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LIFE_TIME 90;

CREATE PROFILE PERFIL_SIGPRA_ASESOR LIMIT
  SESSIONS_PER_USER 2
  CONNECT_TIME 300
  IDLE_TIME 45
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LIFE_TIME 90;

CREATE USER U_SIGPRA_EST IDENTIFIED BY "Sigpra2026*Est"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE PERFIL_SIGPRA_ESTUDIANTE
  QUOTA UNLIMITED ON USERS;

CREATE USER U_SIGPRA_TUTOR IDENTIFIED BY "Sigpra2026*Tut"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE PERFIL_SIGPRA_DOCENTE
  QUOTA UNLIMITED ON USERS;

CREATE USER U_SIGPRA_DIR IDENTIFIED BY "Sigpra2026*Dir"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE PERFIL_SIGPRA_DIRECTOR
  QUOTA UNLIMITED ON USERS;

CREATE USER U_SIGPRA_ASES IDENTIFIED BY "Sigpra2026*Ase"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE PERFIL_SIGPRA_ASESOR
  QUOTA UNLIMITED ON USERS;

PROMPT 2.3) ROLES Y PRIVILEGIOS POR ROL

CREATE ROLE ROL_SIGPRA_ESTUDIANTE;
CREATE ROLE ROL_SIGPRA_TUTOR;
CREATE ROLE ROL_SIGPRA_DIRECTOR;
CREATE ROLE ROL_SIGPRA_ASESOR_PEDAGOGICO;

GRANT CREATE SESSION TO ROL_SIGPRA_ESTUDIANTE;
GRANT CREATE SESSION TO ROL_SIGPRA_TUTOR;
GRANT CREATE SESSION TO ROL_SIGPRA_DIRECTOR;
GRANT CREATE SESSION TO ROL_SIGPRA_ASESOR_PEDAGOGICO;

GRANT SELECT ON usuario TO ROL_SIGPRA_ESTUDIANTE;
GRANT SELECT ON practica TO ROL_SIGPRA_ESTUDIANTE;
GRANT SELECT, INSERT ON actividad_practica TO ROL_SIGPRA_ESTUDIANTE;
GRANT SELECT, INSERT ON evidencia TO ROL_SIGPRA_ESTUDIANTE;
GRANT SELECT, INSERT ON jornada_practica TO ROL_SIGPRA_ESTUDIANTE;

GRANT SELECT ON usuario TO ROL_SIGPRA_TUTOR;
GRANT SELECT, UPDATE ON practica TO ROL_SIGPRA_TUTOR;
GRANT SELECT, UPDATE ON actividad_practica TO ROL_SIGPRA_TUTOR;
GRANT SELECT, INSERT, UPDATE ON evaluacion TO ROL_SIGPRA_TUTOR;
GRANT SELECT, INSERT, UPDATE ON detalle_evaluacion TO ROL_SIGPRA_TUTOR;
GRANT SELECT, INSERT, UPDATE ON reporte_periodo_practica TO ROL_SIGPRA_TUTOR;

GRANT SELECT, UPDATE ON usuario TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, UPDATE ON estudiante TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, UPDATE ON docente_asesor TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, UPDATE ON entidad_receptora TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON plantilla_bitacora TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON pregunta_plantilla_bitacora TO ROL_SIGPRA_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON reporte_periodo_practica TO ROL_SIGPRA_DIRECTOR;

GRANT SELECT ON practica TO ROL_SIGPRA_ASESOR_PEDAGOGICO;
GRANT SELECT ON actividad_practica TO ROL_SIGPRA_ASESOR_PEDAGOGICO;
GRANT SELECT ON jornada_practica TO ROL_SIGPRA_ASESOR_PEDAGOGICO;
GRANT SELECT, INSERT, UPDATE ON validacion_institucional TO ROL_SIGPRA_ASESOR_PEDAGOGICO;
GRANT SELECT ON evidencia TO ROL_SIGPRA_ASESOR_PEDAGOGICO;

GRANT ROL_SIGPRA_ESTUDIANTE TO U_SIGPRA_EST;
GRANT ROL_SIGPRA_TUTOR TO U_SIGPRA_TUTOR;
GRANT ROL_SIGPRA_DIRECTOR TO U_SIGPRA_DIR;
GRANT ROL_SIGPRA_ASESOR_PEDAGOGICO TO U_SIGPRA_ASES;

PROMPT 2.4) PROCEDIMIENTOS ALMACENADOS

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_ACTIVIDAD (
  P_ID_PRACTICA       IN  NUMBER,
  P_FECHA_ACTIVIDAD   IN  DATE,
  P_DESCRIPCION       IN  VARCHAR2,
  P_HORAS             IN  NUMBER,
  P_ID_ACTIVIDAD_OUT  OUT NUMBER
) IS
BEGIN
  INSERT INTO actividad_practica (
    id_actividad, fecha_actividad, descripcion, horas, estado_validacion, comentario_docente, id_practica
  ) VALUES (
    NULL, P_FECHA_ACTIVIDAD, P_DESCRIPCION, P_HORAS, 'PENDIENTE', NULL, P_ID_PRACTICA
  )
  RETURNING id_actividad INTO P_ID_ACTIVIDAD_OUT;

  UPDATE practica
     SET horas_acumuladas = NVL(horas_acumuladas, 0) + P_HORAS,
         estado = CASE
                    WHEN NVL(horas_acumuladas, 0) + P_HORAS >= horas_objetivo THEN 'FINALIZADA'
                    ELSE estado
                  END
   WHERE id_practica = P_ID_PRACTICA;
END;
/

CREATE OR REPLACE PROCEDURE SP_VALIDAR_ACTIVIDAD (
  P_ID_ACTIVIDAD      IN NUMBER,
  P_ESTADO_VALIDACION IN VARCHAR2,
  P_COMENTARIO        IN VARCHAR2
) IS
BEGIN
  UPDATE actividad_practica
     SET estado_validacion = P_ESTADO_VALIDACION,
         comentario_docente = P_COMENTARIO
   WHERE id_actividad = P_ID_ACTIVIDAD;
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_JORNADA (
  P_ID_PRACTICA         IN  NUMBER,
  P_FECHA_JORNADA       IN  DATE,
  P_HORA_INGRESO        IN  VARCHAR2,
  P_HORA_SALIDA         IN  VARCHAR2,
  P_FIRMA_INGRESO       IN  VARCHAR2,
  P_FIRMA_SALIDA        IN  VARCHAR2,
  P_CARGO_FIRMANTE      IN  VARCHAR2,
  P_OBSERVACION         IN  VARCHAR2,
  P_ID_JORNADA_OUT      OUT NUMBER
) IS
  V_HORAS NUMBER;
BEGIN
  V_HORAS := ROUND((
    TO_DATE(P_HORA_SALIDA, 'HH24:MI') - TO_DATE(P_HORA_INGRESO, 'HH24:MI')
  ) * 24, 2);

  INSERT INTO jornada_practica (
    id_jornada, id_practica, fecha_jornada, hora_ingreso, hora_salida,
    horas_registradas, firma_ingreso_nombre, firma_salida_nombre,
    cargo_firmante, estado_validacion, observacion
  ) VALUES (
    NULL, P_ID_PRACTICA, P_FECHA_JORNADA, P_HORA_INGRESO, P_HORA_SALIDA,
    V_HORAS, P_FIRMA_INGRESO, P_FIRMA_SALIDA,
    P_CARGO_FIRMANTE, 'PENDIENTE', P_OBSERVACION
  )
  RETURNING id_jornada INTO P_ID_JORNADA_OUT;
END;
/

CREATE OR REPLACE PROCEDURE SP_CERRAR_PRACTICA (
  P_ID_PRACTICA   IN NUMBER,
  P_ESTADO_FINAL  IN VARCHAR2
) IS
BEGIN
  UPDATE practica
     SET estado = P_ESTADO_FINAL,
         fecha_fin = NVL(fecha_fin, SYSDATE)
   WHERE id_practica = P_ID_PRACTICA;
END;
/

CREATE OR REPLACE PROCEDURE SP_CREAR_REPORTE_PERIODO (
  P_PERIODO          IN  VARCHAR2,
  P_TIPO_REPORTE     IN  VARCHAR2,
  P_TITULO           IN  VARCHAR2,
  P_FECHA_LIMITE     IN  DATE,
  P_ID_RESPONSABLE   IN  NUMBER,
  P_OBSERVACION      IN  VARCHAR2,
  P_ID_REPORTE_OUT   OUT NUMBER
) IS
BEGIN
  INSERT INTO reporte_periodo_practica (
    id_reporte, periodo, tipo_reporte, titulo, fecha_limite,
    fecha_entrega, estado, id_responsable, url_documento, observacion
  ) VALUES (
    NULL, P_PERIODO, P_TIPO_REPORTE, P_TITULO, P_FECHA_LIMITE,
    NULL, 'BORRADOR', P_ID_RESPONSABLE, NULL, P_OBSERVACION
  )
  RETURNING id_reporte INTO P_ID_REPORTE_OUT;
END;
/

PROMPT 2.5) DISPARADORES (referencia y extensiones)
PROMPT Disparadores ya existentes en 01_crear_esquema_oracle.sql y 04_ajustes_reunion_20260310.sql

CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_CUPOS_ENTIDAD_AI
AFTER INSERT ON practica
FOR EACH ROW
BEGIN
  UPDATE entidad_receptora
     SET cupos_disponibles = GREATEST(cupos_disponibles - 1, 0)
   WHERE id_entidad = :NEW.id_entidad;
END;
/

CREATE OR REPLACE TRIGGER TRG_RESTAURAR_CUPOS_ENTIDAD_AD
AFTER DELETE ON practica
FOR EACH ROW
BEGIN
  UPDATE entidad_receptora
     SET cupos_disponibles = LEAST(cupos_disponibles + 1, cupos_totales)
   WHERE id_entidad = :OLD.id_entidad;
END;
/

PROMPT 2.6) REPORTES (consultas)
PROMPT Ejecuta para reportes:
PROMPT @@..\ENTREGA_2_COMPLETA\03_BASE_DATOS\bd\03_consultas_utiles.sql

COMMIT;
PROMPT Script de tercera entrega generado correctamente.
